# Generated by Django 5.1.3 on 2024-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(upload_to='imgs/', verbose_name='Изображение'),
        ),
    ]
